---
name: Yash
version: 0.2
author:
  - 'Olivier Schwander <iderrick@cpan.org>'
abstract: Manipulation of Yaml files in shell scripts
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  YAML: 0
configure_requires:
  Module::Build: 0.340201
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
